-- ========================================================
-- WORKSPACE STRUCTURE COPIER GUI
-- GUI untuk copy detail struktur workspace, bukan script
-- ========================================================

print("🖥️ LOADING WORKSPACE STRUCTURE COPIER...")

local Players = game:GetService("Players")
local Workspace = game:GetService("Workspace")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")

local LocalPlayer = Players.LocalPlayer

-- ========================================================
-- SCANNER DATA
-- ========================================================

local scanResults = {
    pets = {},
    eggs = {},
    effects = {},
    children = {},
    totalObjects = 0,
    scanTime = 0,
    structureText = ""
}

-- ========================================================
-- WORKSPACE STRUCTURE ANALYZER
-- ========================================================

local function scanWorkspaceStructure()
    print("🔍 Analyzing workspace structure...")
    local startTime = tick()
    
    -- Reset results
    scanResults = {
        pets = {},
        eggs = {},
        effects = {},
        children = {},
        totalObjects = 0,
        scanTime = 0,
        structureText = ""
    }
    
    -- Scan top-level workspace children
    for _, child in pairs(Workspace:GetChildren()) do
        pcall(function()
            scanResults.totalObjects = scanResults.totalObjects + 1
            
            table.insert(scanResults.children, {
                name = child.Name,
                className = child.ClassName,
                path = 'game.Workspace.' .. child.Name,
                copyPath = 'game:GetService("Workspace"):FindFirstChild("' .. child.Name .. '")',
                childCount = #child:GetChildren()
            })
            
            local objName = child.Name:lower()
            
            -- Pet detection
            if child:IsA("Model") and (objName:find("pet") or objName:find("companion") or objName:find("follow")) then
                table.insert(scanResults.pets, {
                    name = child.Name,
                    path = 'game.Workspace.' .. child.Name,
                    copyPath = 'game:GetService("Workspace"):FindFirstChild("' .. child.Name .. '")'
                })
            end
        end)
    end
    
    -- Scan for eggs in AreaEggSlotsClient
    local areaEggs = Workspace:FindFirstChild("AreaEggSlotsClient")
    if areaEggs then
        for _, eggModel in pairs(areaEggs:GetChildren()) do
            pcall(function()
                if eggModel:IsA("Model") then
                    table.insert(scanResults.eggs, {
                        name = eggModel.Name,
                        path = 'game.Workspace.AreaEggSlotsClient.' .. eggModel.Name,
                        copyPath = 'game.Workspace.AreaEggSlotsClient:FindFirstChild("' .. eggModel.Name .. '")',
                        childCount = #eggModel:GetChildren()
                    })
                end
            end)
        end
    end
    
    -- Quick effect count
    for _, child in pairs(Workspace:GetChildren()) do
        pcall(function()
            if child:IsA("ParticleEmitter") or child:IsA("Beam") or child:IsA("Trail") then
                table.insert(scanResults.effects, child)
            end
        end)
    end
    
    scanResults.scanTime = math.floor((tick() - startTime) * 1000) / 1000
    
    -- Generate structure text
    generateStructureText()
    
    print("✅ Structure analysis complete!")
    print("   🐾 Pets: " .. #scanResults.pets)
    print("   🥚 Eggs: " .. #scanResults.eggs)
    print("   📁 Children: " .. #scanResults.children)
    print("   ⏱️  Time: " .. scanResults.scanTime .. "s")
end

local function generateStructureText()
    local structureText = [[-- ========================================================
-- WORKSPACE STRUCTURE ANALYSIS
-- Generated by Workspace Structure Copier
-- ========================================================

📊 ANALYSIS SUMMARY:
===================
🐾 Pets found: ]] .. #scanResults.pets .. [[

🥚 Eggs found: ]] .. #scanResults.eggs .. [[

✨ Effects found: ]] .. #scanResults.effects .. [[

📁 Top-level children: ]] .. #scanResults.children .. [[

📦 Total objects scanned: ]] .. scanResults.totalObjects .. [[

⏱️ Analysis time: ]] .. scanResults.scanTime .. [[s

-- ========================================================
-- 📁 WORKSPACE TOP-LEVEL CHILDREN
-- ========================================================

]]

    -- Add workspace children
    for i, child in ipairs(scanResults.children) do
        structureText = structureText .. string.format([[
[%d] %s (%s) - %d children
   📍 Full Path: %s
   📋 Copy Path: %s
   🎯 Direct Access: game.Workspace["%s"]

]], i, child.name, child.className, child.childCount, child.path, child.copyPath, child.name)
    end

    -- Add pets section
    if #scanResults.pets > 0 then
        structureText = structureText .. [[

-- ========================================================
-- 🐾 PETS DETECTED
-- ========================================================

]]
        for i, pet in ipairs(scanResults.pets) do
            structureText = structureText .. string.format([[
Pet %d: %s
   📍 Full Path: %s
   📋 Copy Path: %s
   🗑️  Delete Command: %s.Parent = nil
   👻 Hide Command: for _, part in pairs(%s:GetDescendants()) do
       if part:IsA("BasePart") then part.Transparency = 1; part.CanCollide = false end
   end

]], i, pet.name, pet.path, pet.copyPath, pet.copyPath, pet.copyPath)
        end
    else
        structureText = structureText .. "\n🐾 No pets detected in top-level workspace.\n"
    end

    -- Add eggs section
    if #scanResults.eggs > 0 then
        structureText = structureText .. [[

-- ========================================================
-- 🥚 EGGS DETECTED (AreaEggSlotsClient)
-- ========================================================

AreaEggSlotsClient Location:
📍 Path: game.Workspace.AreaEggSlotsClient
📋 Copy: game:GetService("Workspace"):FindFirstChild("AreaEggSlotsClient")

Individual Eggs:
]]
        for i, egg in ipairs(scanResults.eggs) do
            structureText = structureText .. string.format([[
Egg %d: %s (%d parts)
   📍 Full Path: %s
   📋 Copy Path: %s
   👻 Hide Visual (Keep Hitbox): 
       for _, part in pairs(%s:GetDescendants()) do
           if part:IsA("BasePart") and not part.Name:lower():find("hitbox") then
               part.Transparency = 1
               part.CanCollide = false
               part.CastShadow = false
           end
       end

]], i, egg.name, egg.childCount, egg.path, egg.copyPath, egg.copyPath)
        end
    else
        structureText = structureText .. "\n🥚 No AreaEggSlotsClient found or no eggs detected.\n"
    end

    -- Add quick commands section
    structureText = structureText .. [[

-- ========================================================
-- 🎯 QUICK ACCESS COMMANDS (COPY-PASTE READY)
-- ========================================================

-- Get AreaEggSlotsClient:
local areaEggs = game:GetService("Workspace"):FindFirstChild("AreaEggSlotsClient")

-- List all eggs:
if areaEggs then
    for i, egg in pairs(areaEggs:GetChildren()) do
        print(i, egg.Name, egg.ClassName)
    end
end

-- Find all pets in workspace:
for _, obj in pairs(game.Workspace:GetChildren()) do
    if obj:IsA("Model") and obj.Name:lower():find("pet") then
        print("Pet found:", obj.Name)
    end
end

-- Count workspace children:
print("Workspace has", #game.Workspace:GetChildren(), "top-level children")

-- ========================================================
-- 🚀 MASS HIDE COMMANDS (USE WITH CAUTION)
-- ========================================================

-- Hide all pets (delete method):
for _, obj in pairs(game.Workspace:GetChildren()) do
    if obj:IsA("Model") and obj.Name:lower():find("pet") then
        obj.Parent = nil
    end
end

-- Hide all eggs (transparency method, preserve hitboxes):
local areaEggs = game.Workspace:FindFirstChild("AreaEggSlotsClient")
if areaEggs then
    for _, eggModel in pairs(areaEggs:GetChildren()) do
        for _, part in pairs(eggModel:GetDescendants()) do
            if part:IsA("BasePart") then
                local partName = part.Name:lower()
                if partName:find("hitbox") or partName:find("hit") then
                    part.Transparency = 1  -- Keep hitbox invisible but functional
                else
                    part.Transparency = 1
                    part.CanCollide = false
                    part.CastShadow = false
                end
            end
        end
    end
end

-- Hide all visual effects:
for _, obj in pairs(game.Workspace:GetDescendants()) do
    if obj:IsA("ParticleEmitter") or obj:IsA("Beam") or obj:IsA("Trail") or
       obj:IsA("Fire") or obj:IsA("Smoke") or obj:IsA("Sparkles") then
        obj.Enabled = false
    end
end

-- ========================================================
-- 📋 ANALYSIS COMPLETE - COPY THE TEXT ABOVE
-- ========================================================
]]

    scanResults.structureText = structureText
end

local function copyToClipboard()
    if not scanResults.structureText or scanResults.structureText == "" then
        print("❌ No structure to copy! Please scan first.")
        return false
    end
    
    local success = false
    pcall(function()
        if setclipboard then
            setclipboard(scanResults.structureText)
            success = true
        elseif toclipboard then
            toclipboard(scanResults.structureText)
            success = true
        elseif writeclipboard then
            writeclipboard(scanResults.structureText)
            success = true
        end
    end)
    
    if success then
        print("📋 Workspace structure copied to clipboard!")
        return true
    else
        print("❌ Clipboard not available!")
        return false
    end
end

-- ========================================================
-- GUI CREATION
-- ========================================================

local function createGUI()
    -- Main GUI
    local gui = Instance.new("ScreenGui")
    gui.Name = "WorkspaceStructureGUI"
    gui.ResetOnSpawn = false
    
    pcall(function()
        gui.Parent = LocalPlayer.PlayerGui
    end)
    
    -- Main Frame
    local mainFrame = Instance.new("Frame")
    mainFrame.Name = "MainFrame"
    mainFrame.Size = UDim2.new(0, 500, 0, 400)
    mainFrame.Position = UDim2.new(0.5, -250, 0.5, -200)
    mainFrame.BackgroundColor3 = Color3.fromRGB(35, 35, 35)
    mainFrame.BorderSizePixel = 0
    mainFrame.Parent = gui
    
    -- Corner rounding
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 12)
    corner.Parent = mainFrame
    
    -- Title Bar
    local titleBar = Instance.new("Frame")
    titleBar.Name = "TitleBar"
    titleBar.Size = UDim2.new(1, 0, 0, 50)
    titleBar.BackgroundColor3 = Color3.fromRGB(70, 130, 200)
    titleBar.BorderSizePixel = 0
    titleBar.Parent = mainFrame
    
    local titleCorner = Instance.new("UICorner")
    titleCorner.CornerRadius = UDim.new(0, 12)
    titleCorner.Parent = titleBar
    
    -- Fix title bar corner
    local titleFix = Instance.new("Frame")
    titleFix.Size = UDim2.new(1, 0, 0, 12)
    titleFix.Position = UDim2.new(0, 0, 1, -12)
    titleFix.BackgroundColor3 = Color3.fromRGB(70, 130, 200)
    titleFix.BorderSizePixel = 0
    titleFix.Parent = titleBar
    
    -- Title Text
    local titleText = Instance.new("TextLabel")
    titleText.Size = UDim2.new(1, -60, 1, 0)
    titleText.Position = UDim2.new(0, 15, 0, 0)
    titleText.BackgroundTransparency = 1
    titleText.Text = "📁 WORKSPACE STRUCTURE COPIER"
    titleText.TextColor3 = Color3.fromRGB(255, 255, 255)
    titleText.TextSize = 16
    titleText.Font = Enum.Font.SourceSansBold
    titleText.TextXAlignment = Enum.TextXAlignment.Left
    titleText.Parent = titleBar
    
    -- Close Button
    local closeButton = Instance.new("TextButton")
    closeButton.Size = UDim2.new(0, 30, 0, 30)
    closeButton.Position = UDim2.new(1, -40, 0, 10)
    closeButton.BackgroundColor3 = Color3.fromRGB(255, 100, 100)
    closeButton.Text = "✕"
    closeButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    closeButton.TextSize = 16
    closeButton.Font = Enum.Font.SourceSansBold
    closeButton.BorderSizePixel = 0
    closeButton.Parent = titleBar
    
    local closeCorner = Instance.new("UICorner")
    closeCorner.CornerRadius = UDim.new(0, 6)
    closeCorner.Parent = closeButton
    
    -- Stats Frame
    local statsFrame = Instance.new("Frame")
    statsFrame.Size = UDim2.new(1, -30, 0, 120)
    statsFrame.Position = UDim2.new(0, 15, 0, 65)
    statsFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    statsFrame.BorderSizePixel = 0
    statsFrame.Parent = mainFrame
    
    local statsCorner = Instance.new("UICorner")
    statsCorner.CornerRadius = UDim.new(0, 8)
    statsCorner.Parent = statsFrame
    
    -- Stats Labels
    local statsTitle = Instance.new("TextLabel")
    statsTitle.Size = UDim2.new(1, 0, 0, 25)
    statsTitle.Position = UDim2.new(0, 0, 0, 5)
    statsTitle.BackgroundTransparency = 1
    statsTitle.Text = "📊 STRUCTURE ANALYSIS"
    statsTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
    statsTitle.TextSize = 14
    statsTitle.Font = Enum.Font.SourceSansBold
    statsTitle.Parent = statsFrame
    
    local petsLabel = Instance.new("TextLabel")
    petsLabel.Name = "PetsLabel"
    petsLabel.Size = UDim2.new(0.5, -5, 0, 20)
    petsLabel.Position = UDim2.new(0, 10, 0, 35)
    petsLabel.BackgroundTransparency = 1
    petsLabel.Text = "🐾 Pets: 0"
    petsLabel.TextColor3 = Color3.fromRGB(255, 200, 100)
    petsLabel.TextSize = 12
    petsLabel.Font = Enum.Font.SourceSans
    petsLabel.TextXAlignment = Enum.TextXAlignment.Left
    petsLabel.Parent = statsFrame
    
    local eggsLabel = Instance.new("TextLabel")
    eggsLabel.Name = "EggsLabel"
    eggsLabel.Size = UDim2.new(0.5, -5, 0, 20)
    eggsLabel.Position = UDim2.new(0.5, 5, 0, 35)
    eggsLabel.BackgroundTransparency = 1
    eggsLabel.Text = "🥚 Eggs: 0"
    eggsLabel.TextColor3 = Color3.fromRGB(100, 255, 100)
    eggsLabel.TextSize = 12
    eggsLabel.Font = Enum.Font.SourceSans
    eggsLabel.TextXAlignment = Enum.TextXAlignment.Left
    eggsLabel.Parent = statsFrame
    
    local childrenLabel = Instance.new("TextLabel")
    childrenLabel.Name = "ChildrenLabel"
    childrenLabel.Size = UDim2.new(0.5, -5, 0, 20)
    childrenLabel.Position = UDim2.new(0, 10, 0, 60)
    childrenLabel.BackgroundTransparency = 1
    childrenLabel.Text = "📁 Children: 0"
    childrenLabel.TextColor3 = Color3.fromRGB(150, 200, 255)
    childrenLabel.TextSize = 12
    childrenLabel.Font = Enum.Font.SourceSans
    childrenLabel.TextXAlignment = Enum.TextXAlignment.Left
    childrenLabel.Parent = statsFrame
    
    local totalLabel = Instance.new("TextLabel")
    totalLabel.Name = "TotalLabel"
    totalLabel.Size = UDim2.new(0.5, -5, 0, 20)
    totalLabel.Position = UDim2.new(0.5, 5, 0, 60)
    totalLabel.BackgroundTransparency = 1
    totalLabel.Text = "📦 Total: 0"
    totalLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
    totalLabel.TextSize = 12
    totalLabel.Font = Enum.Font.SourceSans
    totalLabel.TextXAlignment = Enum.TextXAlignment.Left
    totalLabel.Parent = statsFrame
    
    local timeLabel = Instance.new("TextLabel")
    timeLabel.Name = "TimeLabel"
    timeLabel.Size = UDim2.new(1, -20, 0, 20)
    timeLabel.Position = UDim2.new(0, 10, 0, 85)
    timeLabel.BackgroundTransparency = 1
    timeLabel.Text = "⏱️ Analysis time: 0.0s"
    timeLabel.TextColor3 = Color3.fromRGB(150, 150, 150)
    timeLabel.TextSize = 11
    timeLabel.Font = Enum.Font.SourceSans
    timeLabel.TextXAlignment = Enum.TextXAlignment.Left
    timeLabel.Parent = statsFrame
    
    -- Preview Frame
    local previewFrame = Instance.new("Frame")
    previewFrame.Size = UDim2.new(1, -30, 0, 120)
    previewFrame.Position = UDim2.new(0, 15, 0, 200)
    previewFrame.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
    previewFrame.BorderSizePixel = 0
    previewFrame.Parent = mainFrame
    
    local previewCorner = Instance.new("UICorner")
    previewCorner.CornerRadius = UDim.new(0, 8)
    previewCorner.Parent = previewFrame
    
    -- Preview Title
    local previewTitle = Instance.new("TextLabel")
    previewTitle.Size = UDim2.new(1, 0, 0, 25)
    previewTitle.BackgroundTransparency = 1
    previewTitle.Text = "👀 STRUCTURE PREVIEW"
    previewTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
    previewTitle.TextSize = 14
    previewTitle.Font = Enum.Font.SourceSansBold
    previewTitle.Parent = previewFrame
    
    -- Preview Text (Scrollable)
    local previewScroll = Instance.new("ScrollingFrame")
    previewScroll.Size = UDim2.new(1, -20, 1, -35)
    previewScroll.Position = UDim2.new(0, 10, 0, 30)
    previewScroll.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
    previewScroll.BorderSizePixel = 0
    previewScroll.ScrollBarThickness = 6
    previewScroll.Parent = previewFrame
    
    local previewText = Instance.new("TextLabel")
    previewText.Name = "PreviewText"
    previewText.Size = UDim2.new(1, -10, 1, 0)
    previewText.Position = UDim2.new(0, 5, 0, 0)
    previewText.BackgroundTransparency = 1
    previewText.Text = "Click 'ANALYZE STRUCTURE' to see workspace details..."
    previewText.TextColor3 = Color3.fromRGB(200, 200, 200)
    previewText.TextSize = 10
    previewText.Font = Enum.Font.Code
    previewText.TextXAlignment = Enum.TextXAlignment.Left
    previewText.TextYAlignment = Enum.TextYAlignment.Top
    previewText.TextWrapped = true
    previewText.Parent = previewScroll
    
    -- Buttons Frame
    local buttonsFrame = Instance.new("Frame")
    buttonsFrame.Size = UDim2.new(1, -30, 0, 60)
    buttonsFrame.Position = UDim2.new(0, 15, 0, 330)
    buttonsFrame.BackgroundTransparency = 1
    buttonsFrame.Parent = mainFrame
    
    -- Analyze Button
    local analyzeButton = Instance.new("TextButton")
    analyzeButton.Name = "AnalyzeButton"
    analyzeButton.Size = UDim2.new(0.48, 0, 0, 35)
    analyzeButton.Position = UDim2.new(0, 0, 0, 0)
    analyzeButton.BackgroundColor3 = Color3.fromRGB(100, 180, 100)
    analyzeButton.Text = "📁 ANALYZE STRUCTURE"
    analyzeButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    analyzeButton.TextSize = 13
    analyzeButton.Font = Enum.Font.SourceSansBold
    analyzeButton.BorderSizePixel = 0
    analyzeButton.Parent = buttonsFrame
    
    local analyzeCorner = Instance.new("UICorner")
    analyzeCorner.CornerRadius = UDim.new(0, 8)
    analyzeCorner.Parent = analyzeButton
    
    -- Copy Button
    local copyButton = Instance.new("TextButton")
    copyButton.Name = "CopyButton"
    copyButton.Size = UDim2.new(0.48, 0, 0, 35)
    copyButton.Position = UDim2.new(0.52, 0, 0, 0)
    copyButton.BackgroundColor3 = Color3.fromRGB(100, 150, 255)
    copyButton.Text = "📋 COPY STRUCTURE"
    copyButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    copyButton.TextSize = 13
    copyButton.Font = Enum.Font.SourceSansBold
    copyButton.BorderSizePixel = 0
    copyButton.Parent = buttonsFrame
    
    local copyCorner = Instance.new("UICorner")
    copyCorner.CornerRadius = UDim.new(0, 8)
    copyCorner.Parent = copyButton
    
    -- Status Label
    local statusLabel = Instance.new("TextLabel")
    statusLabel.Name = "StatusLabel"
    statusLabel.Size = UDim2.new(1, 0, 0, 20)
    statusLabel.Position = UDim2.new(0, 0, 0, 40)
    statusLabel.BackgroundTransparency = 1
    statusLabel.Text = "💡 Click ANALYZE to scan workspace structure"
    statusLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
    statusLabel.TextSize = 11
    statusLabel.Font = Enum.Font.SourceSans
    statusLabel.Parent = buttonsFrame
    
    -- ========================================================
    -- BUTTON FUNCTIONS
    -- ========================================================
    
    local function updateStats()
        petsLabel.Text = "🐾 Pets: " .. #scanResults.pets
        eggsLabel.Text = "🥚 Eggs: " .. #scanResults.eggs
        childrenLabel.Text = "📁 Children: " .. #scanResults.children
        totalLabel.Text = "📦 Total: " .. scanResults.totalObjects
        timeLabel.Text = "⏱️ Analysis time: " .. scanResults.scanTime .. "s"
    end
    
    local function updatePreview()
        if scanResults.structureText and scanResults.structureText ~= "" then
            -- Show first 1000 characters as preview
            local previewLength = 1000
            local preview = string.sub(scanResults.structureText, 1, previewLength)
            if #scanResults.structureText > previewLength then
                preview = preview .. "\n\n... (truncated - full text available via copy button)"
            end
            previewText.Text = preview
            
            -- Update canvas size for scrolling
            previewText.Size = UDim2.new(1, -10, 0, previewText.TextBounds.Y + 10)
            previewScroll.CanvasSize = UDim2.new(0, 0, 0, previewText.TextBounds.Y + 20)
        end
    end
    
    analyzeButton.MouseButton1Click:Connect(function()
        -- Button animation
        local tween = TweenService:Create(analyzeButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(80, 144, 80)})
        tween:Play()
        tween.Completed:Connect(function()
            TweenService:Create(analyzeButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(100, 180, 100)}):Play()
        end)
        
        statusLabel.Text = "📁 Analyzing workspace structure..."
        analyzeButton.Text = "⏳ ANALYZING..."
        
        task.spawn(function()
            scanWorkspaceStructure()
            
            updateStats()
            updatePreview()
            analyzeButton.Text = "📁 ANALYZE STRUCTURE"
            statusLabel.Text = "✅ Analysis complete! Structure ready to copy."
        end)
    end)
    
    copyButton.MouseButton1Click:Connect(function()
        -- Button animation
        local tween = TweenService:Create(copyButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(80, 120, 200)})
        tween:Play()
        tween.Completed:Connect(function()
            TweenService:Create(copyButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(100, 150, 255)}):Play()
        end)
        
        if copyToClipboard() then
            statusLabel.Text = "📋 Workspace structure copied to clipboard!"
            copyButton.Text = "✅ COPIED!"
            task.wait(1.5)
            copyButton.Text = "📋 COPY STRUCTURE"
        else
            statusLabel.Text = "❌ Copy failed! Clipboard not available."
        end
    end)
    
    closeButton.MouseButton1Click:Connect(function()
        gui:Destroy()
    end)
    
    -- Make draggable
    local dragging = false
    local dragStart, startPos
    
    titleBar.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            dragStart = input.Position
            startPos = mainFrame.Position
        end
    end)
    
    UserInputService.InputChanged:Connect(function(input)
        if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then
            local delta = input.Position - dragStart
            mainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end)
    
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = false
        end
    end)
    
    print("✅ GUI loaded successfully!")
    return gui
end

-- ========================================================
-- MAIN EXECUTION
-- ========================================================

print("🚀 Creating Workspace Structure Copier GUI...")
local gui = createGUI()

print("✅ WORKSPACE STRUCTURE COPIER READY!")
print("====================================")
print("📁 GUI created and ready to use")
print("🔍 Click 'ANALYZE STRUCTURE' to scan workspace")
print("📋 Click 'COPY STRUCTURE' to copy detailed info")
print("👀 View preview of structure in GUI")
print("====================================")
print("📋 Copy workspace paths, names, and details!")