-- ========================================================
-- WORKSPACE SCANNER GUI - SIMPLE & EASY
-- Simple GUI with Scan and Copy buttons
-- ========================================================

print("🖥️ LOADING WORKSPACE SCANNER GUI...")

local Players = game:GetService("Players")
local Workspace = game:GetService("Workspace")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")

local LocalPlayer = Players.LocalPlayer

-- ========================================================
-- SCANNER DATA
-- ========================================================

local scanResults = {
    pets = {},
    eggs = {},
    effects = {},
    totalObjects = 0,
    scanTime = 0,
    hideScript = ""
}

-- ========================================================
-- SCANNER FUNCTIONS
-- ========================================================

local function scanWorkspace()
    print("🔍 Starting workspace analysis...")
    local startTime = tick()
    
    -- Reset results
    scanResults = {
        pets = {},
        eggs = {},
        effects = {},
        totalObjects = 0,
        scanTime = 0,
        hideScript = ""
    }
    
    -- Scan workspace efficiently
    pcall(function()
        -- Count total objects first (quick count)
        for _, obj in pairs(Workspace:GetChildren()) do
            scanResults.totalObjects = scanResults.totalObjects + 1
            
            -- Also count their immediate children
            for _, child in pairs(obj:GetChildren()) do
                scanResults.totalObjects = scanResults.totalObjects + 1
            end
        end
        
        -- Scan for pets in player characters
        for _, player in pairs(Players:GetPlayers()) do
            if player.Character then
                for _, obj in pairs(player.Character:GetChildren()) do
                    local objName = obj.Name:lower()
                    if obj:IsA("Model") and (objName:find("pet") or objName:find("companion")) then
                        table.insert(scanResults.pets, {
                            name = obj.Name,
                            path = 'game.Players["' .. player.Name .. '"].Character["' .. obj.Name .. '"]'
                        })
                    end
                end
            end
        end
        
        -- Scan for pets in workspace
        for _, obj in pairs(Workspace:GetChildren()) do
            local objName = obj.Name:lower()
            if obj:IsA("Model") and (objName:find("pet") or objName:find("companion") or objName:find("follow")) then
                table.insert(scanResults.pets, {
                    name = obj.Name,
                    path = 'game.Workspace["' .. obj.Name .. '"]'
                })
            end
        end
        
        -- Scan for eggs in AreaEggSlotsClient
        local areaEggs = Workspace:FindFirstChild("AreaEggSlotsClient")
        if areaEggs then
            for _, eggModel in pairs(areaEggs:GetChildren()) do
                if eggModel:IsA("Model") then
                    table.insert(scanResults.eggs, {
                        name = eggModel.Name,
                        path = 'game.Workspace.AreaEggSlotsClient["' .. eggModel.Name .. '"]'
                    })
                end
            end
        end
        
        -- Quick effect count (sample first 100 objects)
        local effectCount = 0
        local sampleSize = 0
        for _, obj in pairs(Workspace:GetChildren()) do
            sampleSize = sampleSize + 1
            if obj:IsA("ParticleEmitter") or obj:IsA("Beam") or obj:IsA("Trail") then
                effectCount = effectCount + 1
            end
            if sampleSize >= 100 then break end
        end
        
        -- Create dummy effect entries for count
        for i = 1, effectCount * 3 do -- Estimate 3x more effects in full workspace
            table.insert(scanResults.effects, {estimated = true})
        end
    end)
    
    scanResults.scanTime = math.floor((tick() - startTime) * 1000) / 1000
    
    -- Generate hide script
    generateHideScript()
    
    print("✅ Analysis complete!")
    print("   🐾 Pets found: " .. #scanResults.pets)
    print("   🥚 Eggs found: " .. #scanResults.eggs)
    print("   ✨ Effects estimated: " .. #scanResults.effects)
    print("   📊 Total objects: " .. scanResults.totalObjects)
    print("   ⏱️ Analysis time: " .. scanResults.scanTime .. "s")
    
    return true
end

local function generateHideScript()
    local script = [[-- ========================================================
-- AUTO-GENERATED HIDE SCRIPT
-- Generated by Complete Workspace Scanner GUI
-- Found: ]] .. #scanResults.pets .. [[ pets, ]] .. #scanResults.eggs .. [[ eggs, ]] .. #scanResults.effects .. [[ effects
-- ========================================================

print("🚀 Executing hide script...")
print("📊 Targets: ]] .. #scanResults.pets .. [[ pets, ]] .. #scanResults.eggs .. [[ eggs, ]] .. #scanResults.effects .. [[ effects")

local hidden = {pets = 0, eggs = 0, effects = 0}

]]

    -- Add pet hiding commands
    if #scanResults.pets > 0 then
        script = script .. "-- HIDE PETS (" .. #scanResults.pets .. " found)\n"
        for i, pet in ipairs(scanResults.pets) do
            script = script .. 'pcall(function() ' .. pet.path .. '.Parent = nil; hidden.pets = hidden.pets + 1; print("🐾 Hidden pet: ' .. pet.name .. '") end)\n'
        end
        script = script .. "\n"
    else
        script = script .. "-- NO PETS FOUND TO HIDE\n\n"
    end
    
    -- Add egg hiding commands
    if #scanResults.eggs > 0 then
        script = script .. "-- HIDE EGGS (" .. #scanResults.eggs .. " found, preserve hitboxes)\n"
        script = script .. [[local areaEggs = game:GetService("Workspace").AreaEggSlotsClient
if areaEggs then
    for _, eggModel in pairs(areaEggs:GetChildren()) do
        pcall(function()
            if eggModel:IsA("Model") then
                for _, part in pairs(eggModel:GetDescendants()) do
                    if part:IsA("BasePart") then
                        local partName = part.Name:lower()
                        if partName:find("hitbox") or partName:find("hit") then
                            part.Transparency = 1 -- Keep functional
                        else
                            part.Transparency = 1
                            part.CanCollide = false
                            part.CastShadow = false
                        end
                    elseif part:IsA("ParticleEmitter") or part:IsA("Beam") then
                        part.Enabled = false
                    end
                end
                hidden.eggs = hidden.eggs + 1
            end
        end)
    end
    print("🥚 Hidden " .. hidden.eggs .. " eggs (hitboxes preserved)")
else
    print("⚠️ AreaEggSlotsClient not found!")
end

]]
    else
        script = script .. "-- NO EGGS FOUND TO HIDE\n\n"
    end
    
    -- Add effects hiding
    script = script .. "-- HIDE EFFECTS (estimated: " .. #scanResults.effects .. ")\n"
    script = script .. [[for _, obj in pairs(game.Workspace:GetDescendants()) do
    pcall(function()
        if obj:IsA("ParticleEmitter") or obj:IsA("Beam") or obj:IsA("Trail") or 
           obj:IsA("Fire") or obj:IsA("Smoke") or obj:IsA("Sparkles") then
            obj.Enabled = false
            hidden.effects = hidden.effects + 1
        end
    end)
end

]]

    -- Add results
    script = script .. [[-- RESULTS
print("✅ HIDE COMPLETE!")
print("==================")
print("🐾 Pets hidden: " .. hidden.pets)
print("🥚 Eggs hidden: " .. hidden.eggs .. " (hitboxes preserved)")
print("✨ Effects disabled: " .. hidden.effects)
print("🎯 Ready for maximum performance!")

if hidden.pets > 0 or hidden.eggs > 0 or hidden.effects > 0 then
    print("🎉 SUCCESS! Objects hidden successfully!")
else
    print("⚠️ No objects were hidden - check if targets exist!")
end
]]

    scanResults.hideScript = script
    
    -- Debug output
    print("📝 Generated hide script:")
    print("   Length: " .. string.len(script) .. " characters")
    print("   Pets commands: " .. #scanResults.pets)
    print("   Eggs: " .. (#scanResults.eggs > 0 and "Yes" or "No"))
    print("   Effects: Yes")
end

local function copyToClipboard()
    -- Force regenerate script if empty
    if not scanResults.hideScript or scanResults.hideScript == "" then
        print("🔄 Regenerating hide script...")
        generateHideScript()
    end
    
    -- Check if we have any data to copy
    if (#scanResults.pets == 0 and #scanResults.eggs == 0) then
        print("⚠️ No pets or eggs found to hide!")
        return "no_data"
    end
    
    local success = false
    local method = ""
    
    pcall(function()
        if setclipboard then
            setclipboard(scanResults.hideScript)
            success = true
            method = "setclipboard"
        elseif toclipboard then
            toclipboard(scanResults.hideScript)
            success = true
            method = "toclipboard"
        elseif writeclipboard then
            writeclipboard(scanResults.hideScript)
            success = true
            method = "writeclipboard"
        end
    end)
    
    if success then
        print("📋 Script copied to clipboard! (" .. method .. ")")
        print("📊 Script contains:")
        print("   🐾 " .. #scanResults.pets .. " pets to hide")
        print("   🥚 " .. #scanResults.eggs .. " eggs to hide")
        print("   ✨ " .. #scanResults.effects .. " effects to disable")
        return true
    else
        print("❌ Clipboard not available! Trying alternative...")
        -- Show script in console as backup
        print("📋 COPY THIS SCRIPT MANUALLY:")
        print("=" .. string.rep("=", 50))
        print(scanResults.hideScript)
        print("=" .. string.rep("=", 50))
        return "manual_copy"
    end
end

-- ========================================================
-- GUI CREATION
-- ========================================================

local function createGUI()
    -- Main GUI
    local gui = Instance.new("ScreenGui")
    gui.Name = "WorkspaceScannerGUI"
    gui.ResetOnSpawn = false
    
    pcall(function()
        gui.Parent = LocalPlayer.PlayerGui
    end)
    
    -- Main Frame
    local mainFrame = Instance.new("Frame")
    mainFrame.Name = "MainFrame"
    mainFrame.Size = UDim2.new(0, 400, 0, 300)
    mainFrame.Position = UDim2.new(0.5, -200, 0.5, -150)
    mainFrame.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
    mainFrame.BorderSizePixel = 0
    mainFrame.Parent = gui
    
    -- Corner rounding
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, 12)
    corner.Parent = mainFrame
    
    -- Drop shadow effect
    local shadow = Instance.new("Frame")
    shadow.Name = "Shadow"
    shadow.Size = UDim2.new(1, 6, 1, 6)
    shadow.Position = UDim2.new(0, -3, 0, 3)
    shadow.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    shadow.BackgroundTransparency = 0.5
    shadow.BorderSizePixel = 0
    shadow.ZIndex = mainFrame.ZIndex - 1
    shadow.Parent = mainFrame
    
    local shadowCorner = Instance.new("UICorner")
    shadowCorner.CornerRadius = UDim.new(0, 12)
    shadowCorner.Parent = shadow
    
    -- Title Bar
    local titleBar = Instance.new("Frame")
    titleBar.Name = "TitleBar"
    titleBar.Size = UDim2.new(1, 0, 0, 50)
    titleBar.BackgroundColor3 = Color3.fromRGB(50, 150, 250)
    titleBar.BorderSizePixel = 0
    titleBar.Parent = mainFrame
    
    local titleCorner = Instance.new("UICorner")
    titleCorner.CornerRadius = UDim.new(0, 12)
    titleCorner.Parent = titleBar
    
    -- Fix title bar corner (only top corners)
    local titleFix = Instance.new("Frame")
    titleFix.Size = UDim2.new(1, 0, 0, 12)
    titleFix.Position = UDim2.new(0, 0, 1, -12)
    titleFix.BackgroundColor3 = Color3.fromRGB(50, 150, 250)
    titleFix.BorderSizePixel = 0
    titleFix.Parent = titleBar
    
    -- Title Text
    local titleText = Instance.new("TextLabel")
    titleText.Name = "TitleText"
    titleText.Size = UDim2.new(1, -60, 1, 0)
    titleText.Position = UDim2.new(0, 15, 0, 0)
    titleText.BackgroundTransparency = 1
    titleText.Text = "🔍 WORKSPACE SCANNER"
    titleText.TextColor3 = Color3.fromRGB(255, 255, 255)
    titleText.TextSize = 18
    titleText.Font = Enum.Font.SourceSansBold
    titleText.TextXAlignment = Enum.TextXAlignment.Left
    titleText.Parent = titleBar
    
    -- Close Button
    local closeButton = Instance.new("TextButton")
    closeButton.Name = "CloseButton"
    closeButton.Size = UDim2.new(0, 30, 0, 30)
    closeButton.Position = UDim2.new(1, -40, 0, 10)
    closeButton.BackgroundColor3 = Color3.fromRGB(255, 100, 100)
    closeButton.Text = "✕"
    closeButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    closeButton.TextSize = 16
    closeButton.Font = Enum.Font.SourceSansBold
    closeButton.BorderSizePixel = 0
    closeButton.Parent = titleBar
    
    local closeCorner = Instance.new("UICorner")
    closeCorner.CornerRadius = UDim.new(0, 6)
    closeCorner.Parent = closeButton
    
    -- Stats Frame
    local statsFrame = Instance.new("Frame")
    statsFrame.Name = "StatsFrame"
    statsFrame.Size = UDim2.new(1, -30, 0, 120)
    statsFrame.Position = UDim2.new(0, 15, 0, 65)
    statsFrame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    statsFrame.BorderSizePixel = 0
    statsFrame.Parent = mainFrame
    
    local statsCorner = Instance.new("UICorner")
    statsCorner.CornerRadius = UDim.new(0, 8)
    statsCorner.Parent = statsFrame
    
    -- Stats Labels
    local statsTitle = Instance.new("TextLabel")
    statsTitle.Size = UDim2.new(1, 0, 0, 25)
    statsTitle.Position = UDim2.new(0, 0, 0, 5)
    statsTitle.BackgroundTransparency = 1
    statsTitle.Text = "📊 SCAN RESULTS"
    statsTitle.TextColor3 = Color3.fromRGB(255, 255, 255)
    statsTitle.TextSize = 14
    statsTitle.Font = Enum.Font.SourceSansBold
    statsTitle.Parent = statsFrame
    
    local petsLabel = Instance.new("TextLabel")
    petsLabel.Name = "PetsLabel"
    petsLabel.Size = UDim2.new(0.5, -5, 0, 20)
    petsLabel.Position = UDim2.new(0, 10, 0, 35)
    petsLabel.BackgroundTransparency = 1
    petsLabel.Text = "🐾 Pets: 0"
    petsLabel.TextColor3 = Color3.fromRGB(255, 200, 100)
    petsLabel.TextSize = 12
    petsLabel.Font = Enum.Font.SourceSans
    petsLabel.TextXAlignment = Enum.TextXAlignment.Left
    petsLabel.Parent = statsFrame
    
    local eggsLabel = Instance.new("TextLabel")
    eggsLabel.Name = "EggsLabel"
    eggsLabel.Size = UDim2.new(0.5, -5, 0, 20)
    eggsLabel.Position = UDim2.new(0.5, 5, 0, 35)
    eggsLabel.BackgroundTransparency = 1
    eggsLabel.Text = "🥚 Eggs: 0"
    eggsLabel.TextColor3 = Color3.fromRGB(100, 255, 100)
    eggsLabel.TextSize = 12
    eggsLabel.Font = Enum.Font.SourceSans
    eggsLabel.TextXAlignment = Enum.TextXAlignment.Left
    eggsLabel.Parent = statsFrame
    
    local effectsLabel = Instance.new("TextLabel")
    effectsLabel.Name = "EffectsLabel"
    effectsLabel.Size = UDim2.new(0.5, -5, 0, 20)
    effectsLabel.Position = UDim2.new(0, 10, 0, 60)
    effectsLabel.BackgroundTransparency = 1
    effectsLabel.Text = "✨ Effects: 0"
    effectsLabel.TextColor3 = Color3.fromRGB(255, 100, 255)
    effectsLabel.TextSize = 12
    effectsLabel.Font = Enum.Font.SourceSans
    effectsLabel.TextXAlignment = Enum.TextXAlignment.Left
    effectsLabel.Parent = statsFrame
    
    local totalLabel = Instance.new("TextLabel")
    totalLabel.Name = "TotalLabel"
    totalLabel.Size = UDim2.new(0.5, -5, 0, 20)
    totalLabel.Position = UDim2.new(0.5, 5, 0, 60)
    totalLabel.BackgroundTransparency = 1
    totalLabel.Text = "📦 Total: 0"
    totalLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
    totalLabel.TextSize = 12
    totalLabel.Font = Enum.Font.SourceSans
    totalLabel.TextXAlignment = Enum.TextXAlignment.Left
    totalLabel.Parent = statsFrame
    
    local timeLabel = Instance.new("TextLabel")
    timeLabel.Name = "TimeLabel"
    timeLabel.Size = UDim2.new(1, -20, 0, 20)
    timeLabel.Position = UDim2.new(0, 10, 0, 85)
    timeLabel.BackgroundTransparency = 1
    timeLabel.Text = "⏱️ Scan time: 0.0s"
    timeLabel.TextColor3 = Color3.fromRGB(150, 150, 150)
    timeLabel.TextSize = 11
    timeLabel.Font = Enum.Font.SourceSans
    timeLabel.TextXAlignment = Enum.TextXAlignment.Left
    timeLabel.Parent = statsFrame
    
    -- Buttons Frame
    local buttonsFrame = Instance.new("Frame")
    buttonsFrame.Name = "ButtonsFrame"
    buttonsFrame.Size = UDim2.new(1, -30, 0, 80)
    buttonsFrame.Position = UDim2.new(0, 15, 0, 200)
    buttonsFrame.BackgroundTransparency = 1
    buttonsFrame.Parent = mainFrame
    
    -- Scan Button
    local scanButton = Instance.new("TextButton")
    scanButton.Name = "ScanButton"
    scanButton.Size = UDim2.new(0.48, 0, 0, 35)
    scanButton.Position = UDim2.new(0, 0, 0, 0)
    scanButton.BackgroundColor3 = Color3.fromRGB(100, 200, 100)
    scanButton.Text = "🔍 SCAN WORKSPACE"
    scanButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    scanButton.TextSize = 14
    scanButton.Font = Enum.Font.SourceSansBold
    scanButton.BorderSizePixel = 0
    scanButton.Parent = buttonsFrame
    
    local scanCorner = Instance.new("UICorner")
    scanCorner.CornerRadius = UDim.new(0, 8)
    scanCorner.Parent = scanButton
    
    -- Copy Button
    local copyButton = Instance.new("TextButton")
    copyButton.Name = "CopyButton"
    copyButton.Size = UDim2.new(0.48, 0, 0, 35)
    copyButton.Position = UDim2.new(0.52, 0, 0, 0)
    copyButton.BackgroundColor3 = Color3.fromRGB(100, 150, 255)
    copyButton.Text = "📋 COPY SCRIPT"
    copyButton.TextColor3 = Color3.fromRGB(255, 255, 255)
    copyButton.TextSize = 14
    copyButton.Font = Enum.Font.SourceSansBold
    copyButton.BorderSizePixel = 0
    copyButton.Parent = buttonsFrame
    
    local copyCorner = Instance.new("UICorner")
    copyCorner.CornerRadius = UDim.new(0, 8)
    copyCorner.Parent = copyButton
    
    -- Status Label
    local statusLabel = Instance.new("TextLabel")
    statusLabel.Name = "StatusLabel"
    statusLabel.Size = UDim2.new(1, 0, 0, 25)
    statusLabel.Position = UDim2.new(0, 0, 0, 45)
    statusLabel.BackgroundTransparency = 1
    statusLabel.Text = "💡 Click SCAN to analyze workspace"
    statusLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
    statusLabel.TextSize = 12
    statusLabel.Font = Enum.Font.SourceSans
    statusLabel.Parent = buttonsFrame
    
    -- ========================================================
    -- BUTTON FUNCTIONS
    -- ========================================================
    
    local function updateStats()
        petsLabel.Text = "🐾 Pets: " .. #scanResults.pets
        eggsLabel.Text = "🥚 Eggs: " .. #scanResults.eggs
        effectsLabel.Text = "✨ Effects: " .. #scanResults.effects
        totalLabel.Text = "📦 Total: " .. scanResults.totalObjects
        timeLabel.Text = "⏱️ Scan time: " .. scanResults.scanTime .. "s"
    end
    
    scanButton.MouseButton1Click:Connect(function()
        -- Button animation
        local tween = TweenService:Create(scanButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(80, 160, 80)})
        tween:Play()
        tween.Completed:Connect(function()
            TweenService:Create(scanButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(100, 200, 100)}):Play()
        end)
        
        statusLabel.Text = "🔍 Scanning workspace..."
        scanButton.Text = "⏳ SCANNING..."
        
        task.wait(0.1)
        scanWorkspace()
        
        updateStats()
        scanButton.Text = "🔍 SCAN WORKSPACE"
        statusLabel.Text = "✅ Scan complete! Ready to copy script."
    end)
    
    copyButton.MouseButton1Click:Connect(function()
        -- Button animation
        local tween = TweenService:Create(copyButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(80, 120, 200)})
        tween:Play()
        tween.Completed:Connect(function()
            TweenService:Create(copyButton, TweenInfo.new(0.1), {BackgroundColor3 = Color3.fromRGB(100, 150, 255)}):Play()
        end)
        
        local result = copyToClipboard()
        
        if result == true then
            statusLabel.Text = "📋 Script copied! Paste and execute to hide objects."
            copyButton.Text = "✅ COPIED!"
            task.wait(2)
            copyButton.Text = "📋 COPY SCRIPT"
        elseif result == "no_data" then
            statusLabel.Text = "⚠️ No pets/eggs found! Try scanning again."
            copyButton.Text = "❌ NO DATA"
            task.wait(2)
            copyButton.Text = "📋 COPY SCRIPT"
        elseif result == "manual_copy" then
            statusLabel.Text = "📋 Script printed in console - copy manually!"
            copyButton.Text = "📝 MANUAL"
            task.wait(2)
            copyButton.Text = "📋 COPY SCRIPT"
        else
            statusLabel.Text = "❌ Copy failed! Check console for manual copy."
            copyButton.Text = "❌ FAILED"
            task.wait(2)
            copyButton.Text = "📋 COPY SCRIPT"
        end
    end)
    
    closeButton.MouseButton1Click:Connect(function()
        gui:Destroy()
    end)
    
    -- Make draggable
    local dragging = false
    local dragStart, startPos
    
    titleBar.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            dragStart = input.Position
            startPos = mainFrame.Position
        end
    end)
    
    UserInputService.InputChanged:Connect(function(input)
        if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then
            local delta = input.Position - dragStart
            mainFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end)
    
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = false
        end
    end)
    
    print("✅ GUI loaded successfully!")
    return gui
end

-- ========================================================
-- MAIN EXECUTION
-- ========================================================

print("🚀 Creating Workspace Scanner GUI...")
local gui = createGUI()

print("✅ WORKSPACE SCANNER GUI READY!")
print("================================")
print("🖥️ GUI created and ready to use")
print("🔍 Click 'SCAN WORKSPACE' to analyze")
print("📋 Click 'COPY SCRIPT' to get hide script")
print("✕ Click close button to remove GUI")
print("================================")
print("🎯 Simple and effective workspace scanning!")